### ISSUE TITLE
provide a bit more documentation about how the hardware must be connected.

### ISSUE THREAD

**Issue by janvda** [paulhayes/node-red-contrib-usb-hid-relay#1]
I admit I have never heard about USB-HID-relay.

One aspect is not very clear from the readme.
It is about what you need to connect.

I guess you need a raspberry pi (or some other device) running node-red and then you need to connect a "USB A Male - USB B Male" cable with the USB-HID-relay and with one of the USB ports from your raspberry pi.

**Comment by paulhayes** [comment]
Although the ones I've received have been USB-B ports, there may be other models with other types of usb socket, such as female B mini, B micro, or A male.

However I will update the Readme
