### ISSUE TITLE
More a question than problem.

### ISSUE THREAD

**Issue by Just-another-pleb** [paulhayes/node-red-contrib-usb-hid-relay#3]
I love the idea.

Though "not your problem", I am wanting to know if these boards are compatible:

[https://www.banggood.com/search/usb-hid-relay.html?from=nav](url)

Because if they are, that really makes things good for me.

Alas the link doesn't say what "drivers" the board have/use.

**Comment by paulhayes** [comment]
Those look compatible. 

I can't guarantee anything but if you do have problems perhaps together we can add support for them to the library.

**Comment by paulhayes** [comment]
Those look compatible. 

I can't guarantee anything but if you do have problems perhaps together we can add support for them to the library.

**Comment by Just-another-pleb** [comment]
Thanks.

I guess it isn't quite rocket science.  I have some ether net relays which I had to back engineer turning them on/off, so it can't be impossible.

Thanks again.   After I am done with a few projects, I can see a lot of use for the node.

Really good idea.   Thanks.

**Comment by paulhayes** [comment]
Do give them a go, they look compatible. Let me know how you get on.

Node-red is amazing, I've been using it to build the control systems for escape rooms, and the dashboard system is absolutely perfect for the job of generating the operator ui.
